### ISSUE TITLE
Configuration of Janus WebRTC 

### ISSUE THREAD

**Issue by ahmedcharef** [RTippin/messenger-demo#16]
Hi Team!

I have installed Janus WebRTC and I want to configure it with laravel messenger.

I have run the janus with config:

`janus --config conf/janus.plugin.videoroom.jcfg.sample`

It seems that it works fine:

```
...
Loading transport plugin 'libjanus_http.so'...
HTTP webserver started (port 8088, /janus path listener)...
[WARN] HTTPS webserver disabled
[WARN] Admin/monitor HTTP webserver disabled
[WARN] Admin/monitor HTTPS webserver disabled
JANUS REST (HTTP/HTTPS) transport plugin initialized!

```

So I have add below enivrement variable to .env in laravel:

```
JANUS_SERVER_ENDPOINT=http://192.168.126.129:8088/janus
JANUS_SERVER_ADMIN_ENDPOINT=http://192.168.126.129:8088/janus
JANUS_VERIFY_SSL=false
JANUS_DEBUG=true
JANUS_ADMIN_SECRET=
JANUS_API_SECRET=
JANUS_VIDEO_ROOM_SECRET=
JANUS_CLIENT_DEBUG=false
```

The problem is that i the video call is not working, it send session expired:

![image](https://user-images.githubusercontent.com/12074429/172454289-04e823bf-a554-4a0a-a681-096bd86abc0e.png)

please help, thanks in advance.

**Comment by RTippin** [comment]
Firstly, is the job that sets the call up working (and updates the call record in your database with the room ID and secret)? If so, can you see if the room does exists in your janus server?

You should also check your dev console in your browser, both the console logs and the network tab/websockets, and see what errors you find.

The only thing out of place to me is that you did not define an API secret in janus, and you are using their sample config vs `janus.plugin.videoroom.jcfg`. I am not able to give you much direction in the setup of janus itself though.

**Comment by etraeel** [comment]
I have the same problem as you and please let me know if you find a solution. 
Also, if there is a point for installation, state it
tanks

**Comment by RTippin** [comment]
Janus is not directly part of my package / app. I would recommend going through their official [Documentation](https://janus.conf.meetecho.com/docs/index.html) and running the [Echo Test](https://github.com/meetecho/janus-gateway/blob/master/html/echotest.html) locally to ensure your janus server is fully functional first, then also try out the [Video Room Test](https://github.com/meetecho/janus-gateway/blob/master/html/videoroomtest.html), as this should tell you if you have the server configured properly. These demos are the same ones hosted on their website [Here](https://janus.conf.meetecho.com/demos.html) but you would be running them on your own machine.

**Comment by ahmedcharef** [comment]
Hi @

> Janus is not directly part of my package / app. I would recommend going through their official [Documentation](https://janus.conf.meetecho.com/docs/index.html) and running the [Echo Test](https://github.com/meetecho/janus-gateway/blob/master/html/echotest.html) locally to ensure your janus server is fully functional first, then also try out the [Video Room Test](https://github.com/meetecho/janus-gateway/blob/master/html/videoroomtest.html), as this should tell you if you have the server configured properly. These demos are the same ones hosted on their website [Here](https://janus.conf.meetecho.com/demos.html) but you would be running them on your own machine.

Sorry @RTippin but as you can see from below screenshot, the problem is in JanusServer.js, 
![image](https://user-images.githubusercontent.com/12074429/173164172-2e30b9e5-105f-4264-bae2-ee3f348342c5.png)

I have tested the video room from janus official doc and it works fine, also the messenger queue works well too.
![image](https://user-images.githubusercontent.com/12074429/173164351-8f662c38-6167-4f62-a262-42672e97a58e.png)

Can you share the janusServer.js and app.js not minified , hope you can help.

**Comment by RTippin** [comment]
So this demo has my https://github.com/RTippin/messenger-ui and https://github.com/RTippin/janus-client packages installed.

- [janus.php](https://github.com/RTippin/messenger-demo/blob/master/config/janus.php#L20-L30) config settings, check yours.
- [video.blade.php](https://github.com/RTippin/messenger-demo/blob/master/resources/views/vendor/messenger/video.blade.php#L73-L87) you can see the video call blade loading in the configurations
- Here is the [JanusServer](https://github.com/RTippin/messenger-ui/blob/419a3af02e7a84bb9454688db3673429861072d3/resources/js/janus/JanusServer.js) and you can find all the JS [In Here](https://github.com/RTippin/messenger-ui/tree/master/resources/js).

**Comment by etraeel** [comment]
> Firstly, is the job that sets the call up working (and updates the call record in your database with the room ID and secret)? If so, can you see if the room does exists in your janus server?
> 
> You should also check your dev console in your browser, both the console logs and the network tab/websockets, and see what errors you find.
> 
> The only thing out of place to me is that you did not define an API secret in janus, and you are using their sample config vs `janus.plugin.videoroom.jcfg`. I am not able to give you much direction in the setup of janus itself though.


this is my `janus.plugin.videoroom.jcfg` , is it correct??

`
room-1234: {
	description = "Demo Room"
	secret = "adminpwd"
	publishers = 6
	bitrate = 128000
	fir_freq = 10
	#audiocodec = "opus"
	#videocodec = "vp8"
	record = false
	#rec_dir = "/path/to/recordings-folder"
}

room-5678: {
	description = "VP9-SVC Demo Room"
	secret = "adminpwd"
	publishers = 6
	bitrate = 512000
	fir_freq = 10
	videocodec = "vp9"
	video_svc = true
}
`

if not , what should i do?

**Comment by RTippin** [comment]
@etraeel My responses above were for @ahmedcharef . Please read through them as they may apply to you as well. Janus is out of my control, so I can only help if you have it working and only have confusion with how my UI intakes a few config values.

**Comment by RTippin** [comment]
@etraeel Then you need to check your queue and see if the call setup is failing, because that is what "creates" a room with janus via the queued job. Your call should not even be marked with `setup_complete` unless that happened, and the UI is not meant to even try to connect to janus unless the call is marked as such. I don't know which steps you are bypassing here.
