### ISSUE TITLE
invalid element type (room should be a positive integer)

### ISSUE THREAD

**Issue by etraeel** [RTippin/messenger-demo#17]
The following error is displayed when making a video call

![Screenshot from 2022-06-16 10-43-50](https://user-images.githubusercontent.com/75931042/174004287-8c846ad9-e3df-4f4c-8429-ff782a225f03.png)

**Comment by RTippin** [comment]
@etraeel you never replied to the other issue  https://github.com/RTippin/messenger-demo/issues/16 you commented on. What have you tried that led up to your screenshot above? I need more context...like what your dev console shows. I assume your janus is running its websocket interface, so you should be able to see everything in your network tab.
